# Generated by Django 4.1.10 on 2023-08-20 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='url',
            field=models.CharField(max_length=64, validators=[django.core.validators.URLValidator()]),
        ),
    ]
