# Generated by Django 4.1.10 on 2023-08-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0002_alter_entry_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
