# Generated by Django 4.1.10 on 2023-08-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0003_entry_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
