# Generated by Django 4.1.10 on 2023-08-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PasswordManager', '0004_alter_entry_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='key',
        ),
    ]
